/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2026-09-09 07:39:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import in.co.rays.proj4.controller.StudentCtl;
import in.co.rays.proj4.util.ServletUtility;
import in.co.rays.proj4.controller.ORSView;
import java.util.List;
import in.co.rays.proj4.bean.CollegeBean;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.bean.UserBean;

public final class StudentView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1788765838473L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1788938047201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("in.co.rays.proj4.controller.StudentCtl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.CollegeBean");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.rays.proj4.util.ServletUtility");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Student</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	UserBean userBean = (UserBean) session.getAttribute("user");
	String roleName = (String) session.getAttribute("role");
	boolean isLogin = userBean != null;
	String welcomeMsg = "Hi, ";
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr style=\"width: 100%;\">\r\n");
      out.write("			<td style=\"width: 98%;\">\r\n");
      out.write("				");

				if (isLogin) {
				
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("					<h3><b>");
      out.print(welcomeMsg + userBean.getFirstName() + "(" + roleName + ")");
      out.write("</b></h3>\r\n");
      out.write("					<a href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\"><b>Add Role</b></a> | \r\n");
      out.write("					<a href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"><b>Role List</b></a> | \r\n");
      out.write("					<a href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"><b>Add User</b></a> | \r\n");
      out.write("					<a href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><b>User List</b></a> |\r\n");
      out.write("					<a href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><b>Add Student</b></a> | \r\n");
      out.write("					<a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><b>Student List</b></a> |\r\n");
      out.write("					<a href=\"LoginCtl?operation=logout\"><b>Logout</b> </a>\r\n");
      out.write("				</div> ");

                }
                
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("                ");

                if (!isLogin) {
                
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("					<h3>Hi, Guest</h3>\r\n");
      out.write("					<a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"><b>Welcome</b></a> | \r\n");
      out.write("					<a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\"><b>Login</b></a> |\r\n");
      out.write("					<a href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL);
      out.write("\"><b>SignUp</b></a>\r\n");
      out.write("				</div> \r\n");
      out.write("				");

                }
                
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("			<td style=\"width: 2%;\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/customLogo.jpg\" width=\"175\"\r\n");
      out.write("						height=\"50\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String _suc = ServletUtility.getSuccessMessage(request);
	String _err = ServletUtility.getErrorMessage(request);

	List<CollegeBean> collegeList = (List<CollegeBean>) request.getAttribute("collegeList");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<form action=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("			<h1>Add Student</h1>\r\n");
      out.write("\r\n");
      out.write("			<h3 style=\"color: green\">");
      out.print(_suc);
      out.write("</h3>\r\n");
      out.write("			<h3 style=\"color: red\">");
      out.print(_err);
      out.write("</h3>\r\n");
      out.write("\r\n");
      out.write("			<table>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>First Name <font color=\"red\">*</font></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"firstName\"\r\n");
      out.write("						value=\"");
      out.print(ServletUtility.getParameter("firstName", request));
      out.write("\"\r\n");
      out.write("						placeholder=\"Enter first name\"></td>\r\n");
      out.write("					<td style=\"color: red\">");
      out.print(ServletUtility.getErrorMessage("firstName", request));
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<!-- Last Name -->\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>Last Name <font color=\"red\">*</font></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"lastName\"\r\n");
      out.write("						value=\"");
      out.print(ServletUtility.getParameter("lastName", request));
      out.write("\"\r\n");
      out.write("						placeholder=\"Enter last name\"></td>\r\n");
      out.write("					<td style=\"color: red\">");
      out.print(ServletUtility.getErrorMessage("lastName", request));
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>DOB <font color=\"red\">*</font></th>\r\n");
      out.write("					<td><input type=\"date\" name=\"dob\"\r\n");
      out.write("						value=\"");
      out.print(ServletUtility.getParameter("dob", request));
      out.write("\">\r\n");
      out.write("					</td>\r\n");
      out.write("					<td style=\"color: red\">");
      out.print(ServletUtility.getErrorMessage("dob", request));
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>Mobile No <font color=\"red\">*</font></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"mobileNo\"\r\n");
      out.write("						value=\"");
      out.print(ServletUtility.getParameter("mobileNo", request));
      out.write("\"\r\n");
      out.write("						placeholder=\"Enter mobile number\"></td>\r\n");
      out.write("					<td style=\"color: red\">");
      out.print(ServletUtility.getErrorMessage("mobileNo", request));
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>Email <font color=\"red\">*</font></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"email\"\r\n");
      out.write("						value=\"");
      out.print(ServletUtility.getParameter("email", request));
      out.write("\"\r\n");
      out.write("						placeholder=\"Enter email\"></td>\r\n");
      out.write("					<td style=\"color: red\">");
      out.print(ServletUtility.getErrorMessage("email", request));
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>College<font color=\"red\">*</font></th>\r\n");
      out.write("\r\n");
      out.write("					<td><select class='form-control' name=\"collegeId\">\r\n");
      out.write("\r\n");
      out.write("							<option selected value=''>--------Select\r\n");
      out.write("								College--------</option>\r\n");
      out.write("\r\n");
      out.write("							");

							for (CollegeBean cbean : collegeList) {
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print(cbean.getKey());
      out.write("\">\r\n");
      out.write("								");
      out.print(cbean.getValue());
      out.write("\r\n");
      out.write("							</option>\r\n");
      out.write("\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</select></td>\r\n");
      out.write("\r\n");
      out.write("					<td style=\"color: red\">");
      out.print(ServletUtility.getErrorMessage("collegeId", request));
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>College Name</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"collegeName\"\r\n");
      out.write("						value=\"");
      out.print(ServletUtility.getParameter("collegeName", request));
      out.write("\"\r\n");
      out.write("						placeholder=\"Enter college name\"></td>\r\n");
      out.write("					<td style=\"color: red\">");
      out.print(ServletUtility.getErrorMessage("collegeName", request));
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					<td><input type=\"submit\" name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(StudentCtl.OP_SAVE);
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#footer {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<hr>\r\n");
      out.write("		<h3>All rights reserved by Rays EdTech, SunilOS Infotech Pvt Ltd\r\n");
      out.write("			Copyright © 2026</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
